services:
    app:
        image: ghcr.io/meowveloper-edu/db-assignment-2:v1.0.0
        volumes:
            - ..:/workspaces/db-assignment-2
        command: sh -c "mkdir -p ../data && chmod -R +x .. && sleep infinity"
        depends_on:
            - postgres
            - mongo

    postgres:
        image: postgres:14.18
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - ../data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    mongo:
        image: mongo:8.0.12-noble
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ../data/mongo:/data/db
        ports:
            - "27017:27017"
    
    adminer:
        image: adminer:5.3.0
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    mongo-express:
        image: mongo-express:1.0.2-20-alpine3.19
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo 
            ME_CONFIG_MONGODB_PORT: 27017 
            ME_CONFIG_MONGODB_ADMINUSERNAME: user 
            ME_CONFIG_MONGODB_ADMINPASSWORD: password 

            ME_CONFIG_BASICAUTH_USERNAME: user 
            ME_CONFIG_BASICAUTH_PASSWORD: password

        depends_on:
            - mongo